export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export const OPEN_FORM_REGISTER = 'OPEN_FORM_REGISTER';



export const RESET_NOTIFI = 'RESET_NOTIFI';
export const OPEN_NOTIFI_SUCCESS = 'OPEN_NOTIFI_SUCCESS';
export const OPEN_NOTIFI_FAIL = 'OPEN_NOTIFI_FAIL';
export const OPEN_LOGIN_NOTIFI_FAIL = 'OPEN_LOGIN_NOTIFI_FAIL';



